from PyQt5 import QtCore, QtWidgets


class UiDrink:
    def __init__(self, Form):
        Form.setObjectName("Form")
        Form.resize(728, 459)

        self.lImage_1 = QtWidgets.QLabel(Form)
        self.lImage_1.setGeometry(QtCore.QRect(80, 10, 121, 111))
        self.lImage_1.setObjectName("lImage_1")
        self.lName_1 = QtWidgets.QLabel(Form)
        self.lName_1.setGeometry(QtCore.QRect(102, 135, 80, 16))
        self.lName_1.setObjectName("lName_1")
        self.lPrice_1 = QtWidgets.QLabel(Form)
        self.lPrice_1.setGeometry(QtCore.QRect(105, 155, 72, 15))
        self.lPrice_1.setObjectName("lPrice_1")
        self.pbOrder_1 = QtWidgets.QPushButton(Form)
        self.pbOrder_1.setGeometry(QtCore.QRect(90, 180, 93, 41))
        self.pbOrder_1.setObjectName("pbOrder_1")

        self.lImage_2 = QtWidgets.QLabel(Form)
        self.lImage_2.setGeometry(QtCore.QRect(295, 10, 131, 111))
        self.lImage_2.setObjectName("lImage_2")
        self.lName_2 = QtWidgets.QLabel(Form)
        self.lName_2.setGeometry(QtCore.QRect(317, 135, 90, 16))
        self.lName_2.setObjectName("lImage_2")
        self.lPrice_2 = QtWidgets.QLabel(Form)
        self.lPrice_2.setGeometry(QtCore.QRect(325, 155, 72, 15))
        self.lPrice_2.setObjectName("lPrice_2")
        self.pbOrder_2 = QtWidgets.QPushButton(Form)
        self.pbOrder_2.setGeometry(QtCore.QRect(310, 180, 93, 41))
        self.pbOrder_2.setObjectName("pbOrder_2")

        self.lImage_3 = QtWidgets.QLabel(Form)
        self.lImage_3.setGeometry(QtCore.QRect(510, 10, 131, 111))
        self.lImage_3.setObjectName("lImage_3")
        self.lName_3 = QtWidgets.QLabel(Form)
        self.lName_3.setGeometry(QtCore.QRect(537, 135, 91, 16))
        self.lName_3.setObjectName("lName_3")
        self.lPrice_3 = QtWidgets.QLabel(Form)
        self.lPrice_3.setGeometry(QtCore.QRect(545, 155, 72, 15))
        self.lPrice_3.setObjectName("lPrice_3")
        self.pbOrder_3 = QtWidgets.QPushButton(Form)
        self.pbOrder_3.setGeometry(QtCore.QRect(530, 180, 93, 41))
        self.pbOrder_3.setObjectName("pbOrder_3")

        self.lImage_4 = QtWidgets.QLabel(Form)
        self.lImage_4.setGeometry(QtCore.QRect(80, 230, 121, 111))
        self.lImage_4.setObjectName("lImage_4")
        self.lName_4 = QtWidgets.QLabel(Form)
        self.lName_4.setGeometry(QtCore.QRect(80, 355, 150, 16))
        self.lName_4.setObjectName("lName_4")
        self.lPrice_4 = QtWidgets.QLabel(Form)
        self.lPrice_4.setGeometry(QtCore.QRect(105, 375, 72, 15))
        self.lPrice_4.setObjectName("lPrice_4")
        self.pbOrder_4 = QtWidgets.QPushButton(Form)
        self.pbOrder_4.setGeometry(QtCore.QRect(90, 400, 93, 41))
        self.pbOrder_4.setObjectName("pbOrder_4")

        self.lImage_5 = QtWidgets.QLabel(Form)
        self.lImage_5.setGeometry(QtCore.QRect(295, 230, 131, 111))
        self.lImage_5.setObjectName("lImage_5")
        self.lName_5 = QtWidgets.QLabel(Form)
        self.lName_5.setGeometry(QtCore.QRect(320, 355, 131, 16))
        self.lName_5.setObjectName("lName_5")
        self.lPrice_5 = QtWidgets.QLabel(Form)
        self.lPrice_5.setGeometry(QtCore.QRect(325, 375, 72, 15))
        self.lPrice_5.setObjectName("lPrice_5")
        self.pbOrder_5 = QtWidgets.QPushButton(Form)
        self.pbOrder_5.setGeometry(QtCore.QRect(310, 400, 93, 41))
        self.pbOrder_5.setObjectName("pbOrder_5")

        self.pbOrder_back = QtWidgets.QPushButton(Form)
        self.pbOrder_back.setGeometry(QtCore.QRect(600, 400, 93, 41))
        self.pbOrder_back.setObjectName("pbOrder_back")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lImage_1.setText(_translate("Form", "TextLabel"))
        self.lName_1.setText(_translate("Form", "阿馥奇朵™"))
        self.lPrice_1.setText(_translate("Form", "钱1"))
        self.pbOrder_1.setText(_translate("Form", "加入订单"))

        self.lImage_2.setText(_translate("Form", "TextLabel"))
        self.lName_2.setText(_translate("Form", "麦芽雪冷萃™"))
        self.lPrice_2.setText(_translate("Form", "钱2"))
        self.pbOrder_2.setText(_translate("Form", "加入订单"))

        self.lImage_3.setText(_translate("Form", "TextLabel"))
        self.lName_3.setText(_translate("Form", "冷萃浮乐朵™"))
        self.lPrice_3.setText(_translate("Form", "钱3"))
        self.pbOrder_3.setText(_translate("Form", "加入订单"))

        self.lImage_4.setText(_translate("Form", "TextLabel"))
        self.lName_4.setText(_translate("Form", "气致™冷萃浮乐朵™"))
        self.lPrice_4.setText(_translate("Form", "钱4"))
        self.pbOrder_4.setText(_translate("Form", "加入订单"))

        self.lImage_5.setText(_translate("Form", "TextLabel"))
        self.lName_5.setText(_translate("Form", "轻甜奶油冷萃"))
        self.lPrice_5.setText(_translate("Form", "钱5"))
        self.pbOrder_5.setText(_translate("Form", "加入订单"))

        self.pbOrder_back.setText(_translate("Form", "返回"))
